### ISSUE TITLE
Serialization-/Deserialization Callbacks aren't called

### ISSUE THREAD

**Issue by nordic81** [tomba/netserializer#43]
Hi,
I just found out that the OnSerializing / OnSerialized / OnDeserializing / OnDeserialized callbacks aren't called by the serializer.

Any plans on changing that? Calling this methods by ourselves would render the performance boost by the netserializer meaningless and wouldn't even be possible for the OnDeserializing delegate (except there would be a fancy way to write an own serializer for that.

**Comment by tomba** [comment]
Hi,

No, no plans to add those. I have to say I don't remember if the reason I haven't included those was just that I didn't want to add any additional overhead, or if there was some technical issue with the callbacks.

And generally speaking, NetSerializer is not a full-blown serializer. It takes shortcuts to do its job quickly.

Without thinking this totally through, and without looking at the code, I have the gut feeling that it might be possible to add support for the callbacks in a way that would not cause slow-downs for any other objects except those that implement said callbacks.

**Comment by nordic81** [comment]
I already implemented a mechanism in our source code that creates a cache of the appropriate method infos by type when the netserializer is created.
This shouldn't cause much overhead, but to make it really work, it has to be integrated into the serializer itself.
With this technique i can only call OnDeserialized etc. on objects that are directly handed to the serializer. The callbacks still can't be called on any encapsulated object without creating a massive overhead by reflections....

Interested in our source code?

**Comment by tomba** [comment]
I've pushed support for the callbacks into "work" branch. Could you test it?

**Comment by nordic81** [comment]
Thank you, i hope we'll have time to test it this week.

**Comment by nordic81** [comment]
I managed to test the work branch today.
The serialization callbacks are called, but there seems to be an error during deserialization: Even though the OnDeserializing/OnDeserialized Callbacks are correctly called, the state of the deserialized object doesn't change.

It seems as if the callbacks are called on the wrong instance or the wrong instance is returned by the serializer?

**Comment by tomba** [comment]
Do you have a test case? Are you using structs?

**Comment by nordic81** [comment]
Well, I wrote a small unit test showing the problem. I could send you the two classes for the project, but since it's directly wired into our own test library, I guess you would have to modify it a bit.

**Comment by tomba** [comment]
If the classes show what you are serializing, that's enough.

**Comment by nordic81** [comment]
`[DataContract]
    [Serializable]
    internal class CallbackTestClass
    {
        [NonSerialized]
        private bool FOnSerializingCalled;

        [NonSerialized]
        private bool FOnSerializedCalled;

        [NonSerialized]
        private bool FOnDeserializingCalled;

        [NonSerialized]
        private bool FOnDeserializedCalled;

        [DataMember]
        public int Value { get; private set; }

        public CallbackTestClass(int _Value)
        {
            Value = _Value;
        }

        public bool OnSerializingCalled
        {
            get
            {
                return FOnSerializingCalled;
            }
            private set
            {
                FOnSerializingCalled = value;
            }
        }

        public bool OnSerializedCalled
        {
            get
            {
                return FOnSerializedCalled;
            }
            private set
            {
                FOnSerializedCalled = value;
            }
        }

        public bool OnDeserializingCalled
        {
            get
            {
                return FOnDeserializingCalled;
            }
            private set
            {
                FOnDeserializingCalled = value;
            }
        }

        public bool OnDeserializedCalled
        {
            get
            {
                return FOnDeserializedCalled;
            }
            private set
            {
                FOnDeserializedCalled = value;
            }
        }

        [OnSerializing]
        private void OnSerializing(StreamingContext _Context)
        {
            OnSerializingCalled = true;
        }

        [OnDeserializing]
        private void OnDeserializing(StreamingContext _Context)
        {
            OnDeserializingCalled = true;
        }

        [OnSerialized]
        private void OnSerialized(StreamingContext _Context)
        {
            OnSerializedCalled = true;
        }

        [OnDeserialized]
        private void OnDeserialized(StreamingContext _Context)
        {
            OnDeserializedCalled = true;
        }
    }

    [TestFixture]
    public class SerializationCallbackTests
    {
        [Test]
        public void TestSerializationCallbacks([Values(SerializationFormat.Json, SerializationFormat.NetSerializer, SerializationFormat.Xml)] SerializationFormat _SerializationFormat)
        {
            // Arrange
            var hCmdMsgQueue = new CommandMessageQueue();

            var hObj = new CallbackTestClass(42);
            Assert.IsFalse(hObj.OnDeserializedCalled);
            Assert.IsFalse(hObj.OnSerializedCalled);
            Assert.IsFalse(hObj.OnDeserializingCalled);
            Assert.IsFalse(hObj.OnSerializingCalled);
            Assert.AreEqual(42, hObj.Value);

            // Act
            var hStream = hObj.Serialize(hCmdMsgQueue, false, _SerializationFormat);
            Assert.IsFalse(hCmdMsgQueue.HasErrorOrAbort);

            hStream.Position = 0;

            var hDes = SerializationUtils.Deserialize<CallbackTestClass>(hStream, hCmdMsgQueue);
            Assert.IsFalse(hCmdMsgQueue.HasErrorOrAbort);

            // Assert
            Assert.NotNull(hDes);
            Assert.AreNotSame(hDes, hObj);

            Assert.IsFalse(hObj.OnDeserializedCalled);
            Assert.IsTrue(hObj.OnSerializedCalled);
            Assert.IsFalse(hObj.OnDeserializingCalled);
            Assert.IsTrue(hObj.OnSerializingCalled);
            Assert.AreEqual(42, hObj.Value);

            Assert.IsTrue(hDes.OnDeserializedCalled);
            Assert.IsFalse(hDes.OnSerializedCalled);
            Assert.IsTrue(hDes.OnDeserializingCalled);
            Assert.IsFalse(hDes.OnSerializingCalled);
            Assert.AreEqual(42, hDes.Value);
        }
    }`

**Comment by tomba** [comment]
Thanks. I pushed a quick fix to my work branch: a5a21265c2f51f79da45f8d867780dd501b7c2bb. It should fix the issue.

However, I'm not sure why the previous code didn't work. I need to study it a bit more later.

**Comment by tomba** [comment]
Ok, I see the problem. The fix in a5a2126 is not correct either.

**Comment by tomba** [comment]
I pushed a new fix to work branch: 1c37c7d903d458af418e92d93c23f568f170f0c8, I hope it's correct fix this time...

**Comment by nordic81** [comment]
Thanks a lot, works like a charm.
I think I'll write another unit test, just to verify the correctness of the Callbacks, but I'm pretty sure this will work as expected ;)

Are you interested in setting up a unit test project?

**Comment by tomba** [comment]
There may be one problem with the serialization callbacks, which is that when serializing, structs (value types) are passed as value, not reference. So if you have an array of structs, and the structs have serialization callbacks which change the struct fields, those new values are not retained when returning from serialization. However, the changed values should stay there for the OnSerializing, serialize, OnSerialized cycle. I didn't test this, but I think it'll work that way.

Yes, I'm interested in a unit test project. I almost started writing one but I just couldn't gather the energy =). Are you using the unit test system built into visual studio?

**Comment by nordic81** [comment]
Afaik the serialization callbacks only work for objects. So there would be no need to provide support for structs.

We use the nunit framework and the resharper test runner in our company. But as far as i can tell, the MSTest framework and the visual studio test runner also do a pretty good job.
Maybe I'll find the time to send you a unit test project with my tests ported to MSTest and uncoupled from our base libraries.

**Comment by tomba** [comment]
Why would they only work for classes? I don't see anything in the documentation implying that. And there's no technical reason why the callbacks couldn't be called for structs.

**Comment by nordic81** [comment]
As I see it, the documentation refers to "objects".
Additionally, I implemented a unit test, basically doing exactly the same thing as my previous unit test but using structs instead of objects. This unit test fails for all serializers we've implemented yet (DataContract serializer, JSON.net and NetSerializer).

I could now strip down the unit test to find out, which serializer callbacks work and which don't, but I don't think it's worth the effort.

**Comment by tomba** [comment]
Hmm, yes, I'm not sure what they mean with "objects". If I'm not mistaken, usually when there's need to make a distinction with value types and classes, those words are used. And if something doesn't work for value types, it's usually mentioned.

Does your test fail just by giving wrong result, or do DataContract serializer of JSON.net throw an error?

I still don't quite see why the callbacks could not work with structs, but then, I'm fine with supporting just classes. Perhaps I'll make that explicit, and make the serializer throw an error if the callbacks are used on structs. Otherwise someone may spend a lot of time debugging why the callbacks don't work for structs...

**Comment by nordic81** [comment]
The serialization and deserialization both worked fine, the value I would expect to have changed during serialization still got their initial value, so I think the callbacks weren't called at all.
But I didn't dive deep into this, maybe spending 30 minutes for a debug session would bring up more information...

**Comment by tomba** [comment]
I did a quick test with structs and it behaves as I predicted. So, it could be fixed by changing how serialization works, but I think I'll just make NetSerializer throw an error if those callbacks are used for structs.

**Comment by tomba** [comment]
Implemented in v4.1
